name: PostgreSQL Integration Tests

on: [push,pull_request,workflow_dispatch]

jobs:
   build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-8.0, Pharo64-9.0, Pharo64-10, Pharo64-11, Pharo64-12 ]
        rdbms: [ PostgreSQLv12, PostgreSQLv13, PostgreSQLv14, PostgreSQLv15, PostgreSQLv16 ]
    name: ${{ matrix.smalltalk }} + ${{ matrix.rdbms }}
    steps:
      - uses: actions/checkout@v2
      - name: Start PostgreSQL
        run: ./scripts/setup-PostgreSQL.sh
        env:
          RDBMS: ${{ matrix.rdbms }}
      - name: Set up Smalltalk CI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load Image and Run Integration Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalkci/.PostgreSQL.ston
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RDBMS: ${{ matrix.rdbms }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: ${{matrix.os}}-${{matrix.smalltalk}}
          token: ${{ secrets.CODECOV_TOKEN }}
